CREATE TABLE IF NOT EXISTS public.customers (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20) NOT NULL,
    surname varchar(20) NOT NULL,
    age int NOT NULL,
    phone_number varchar(40),
    PRIMARY KEY (id)
);